consoleLoglevel: WARNING
port: 8081
enableWebUI: true

sensors:
  - HotWaterTemp:
      plugin: W1Sensor 
      id: 28-3c01d075a8df
      offset: 1.26
  - MashTunOutTemp:
      plugin: W1Sensor
      id: 28-3c01d075c6ff
      offset: 0.18
  - MashReturnTemp:
      plugin: W1Sensor
      id: 28-3c01d0754b11
      offset: 0.45
  - MashTemp:
      plugin: W1Sensor
      id: 28-3c01d0758cdc
      offset: 0
  - MashAvgTemp:
      plugin: TempAvgSensor
      sensors:
        - MashReturnTemp
        - MashTunOutTemp

actors:
  - Chugger:
      plugin: GPIOActor
      gpio: 14
  - MKII:
      plugin: GPIOActor
      gpio: 15
  - Heater:
      plugin: GPIOActor
      gpio: 18

controllers:
  - HotWaterController:
      plugin: HysteresisLogic
      logicCoeffs:
        allowedOvershoot: 1
        allowedUndershoot: 0.8
        keepHot: yes
      actor:  Heater
      sensor: HotWaterTemp
      initialSetpoint: 150
      initialState: on

extensions:
   - web:
       plugin: SimpleWebView
       endpoints:
        - enable
        - sethotwaterpoint
        - setmashpoint
   - blynk:
      plugin: BlynkLib
      server: 192.168.105.117
      port: 8080
      token: 9wZEmLt-52nkpCzxp1ck2MiHcvcP6_S8

connections:
  ## Sensors
  - HotWaterTemp.temperature => blynk.v1
  - MashTunOutTemp.temperature => blynk.v2
  - MashReturnTemp.temperature => blynk.v3
  - MashTemp.temperature => blynk.v4
  - MashAvgTemp.temperature => blynk.v12
  ## Pumps
  - blynk.v5 => MKII.state
  - blynk.v6 => Chugger.state
  - MKII.power => blynk.v14
  - Chugger.power => blynk.v15
  ## Heater
  - Heater.power => blynk.v7
  - blynk.v8 => HotWaterController.power
  - HotWaterController.automatic => blynk.v13
  - blynk.v9 => HotWaterController.automatic
  - HotWaterController.setpoint => blynk.v10
  - blynk.v11 => HotWaterController.setpoint
  
# - MashController.power=>blynk.v2
  # - HotWaterController.power=>blynk.v4
  # - blynk.v10=>MashController.power
  # - MashTunOut.temperature=>blynk.v5
  # - MashReturn.temperature=>blynk.v6
  # - Mash.temperature=>blynk.v7
  # - HotWaterTemp.temperature=>blynk.v8
  # IIUC, this is for the 
  # - Compressor.power => web.compressorpower
  # - FridgeTemp.temperature => web.fridgetemp
  # - FermTemp.temperature => web.fermtemp
  # - Tilt.temperature => web.tilttemp
  # - web.setpoint => FermController.setpoint
  # - FermController.setpoint => web.setpoint
  # - web.compressor => Compressor.state

