consoleLoglevel: WARNING
port: 8080
enableWebUI: true

sensors:
  - FridgeTemp:
      plugin: W1Sensor 
      id: 28-0120223e13cf
      offset: 0
  - Tilt:
      plugin: TiltSensor

actors:
  - Compressor:
      plugin: USBRelayActor
      id: "0_1"

  - Pump:
      plugin: USBRelayActor
      id: "0_2"

#  - Pump:
#       plugin: GPIOActor
#       gpio: 17
#   - Heater:
#       plugin: GPIOActor
#       gpio: 18
#       pwmFrequency: 2

controllers:
  - FridgeController:
      plugin: HysteresisLogic
      logicCoeffs:
        allowedOvershoot: 0.5
        allowedUndershoot: 0.3
        keepCold: yes
      actor:  Compressor
      sensor: FridgeTemp
      #FridgeTemp
      initialSetpoint: 4
      initialState: on
      
  - FermController:
      plugin: HysteresisLogic
      logicCoeffs:
        allowedOvershoot: 0.5
        allowedUndershoot: 0.0
        keepCold: yes
      actor:  Pump
      sensor: Tilt
      initialSetpoint: 18
      initialState: on
      
extensions:
   - web:
       plugin: SimpleWebView
       endpoints:
        - enable
        - setpoint
        - pump

connections:
  - web.enable=>FridgeController.state
  - web.enable=>FermController.state
  - Compressor.power=>web.compressorpower
  - FridgeTemp.temperature=>web.fridgetemp
  - FermTemp.temperature=>web.fermtemp
  - Tilt.temperature=>web.tilttemp
  - web.setpoint=>FermController.setpoint
  - FermController.setpoint=>web.setpoint
  - web.compressor=>Compressor.state

