consoleLoglevel: WARNING
port: 8080
enableWebUI: true

sensors:
  - Tilt:
      plugin: TiltSensor
      mac: 'e6:6f:d2:76:43:8d'
      uuid: 'a495bb10c5b14b44b5121370f02d74de'

actors:
  - Pump:
      plugin: DummyActor
      id: "0_2"

#  - Pump:
#       plugin: GPIOActor
#       gpio: 17
#   - Heater:
#       plugin: GPIOActor
#       gpio: 18
#       pwmFrequency: 2

controllers:
  - FermController:
      plugin: HysteresisLogic
      logicCoeffs:
        allowedOvershoot: 0.5
        allowedUndershoot: 0.0
        keepCold: yes
      actor:  Pump
      sensor: Tilt
      initialSetpoint: 20
      initialState: on
      
extensions:
   - web:
       plugin: SimpleWebView
       endpoints:
        - enable
        - setpoint
        - pump

connections:
  - web.enable=>FermController.state
  - FermTemp.temperature=>web.fermtemp
  - Tilt.temperature=>web.tilttemp
  - web.setpoint=>FermController.setpoint
  - FermController.setpoint=>web.setpoint
  - web.compressor=>Compressor.state

